version: '3.9'
services:
  metabase-oracle:
    build: metabase-oracle/.
    container_name: metabase-oracle
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-app-db"
    cpus: 1
    mem_limit: 2048m
    networks: 
      - metanet1-oracle
    depends_on: 
      postgres-app-db-oracle:
        condition: service_healthy
      oracle:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "while ! curl -s 'http://localhost:3000/api/health' | grep '{\"status\":\"ok\"}'; do sleep 1; done"]
  postgres-app-db-oracle:
    image: postgres:14.5-alpine
    container_name: postgres-app-db-oracle
    hostname: postgres-app-db
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1-oracle
    cpus: 1
    mem_limit: 128m
    command: -c log_statement=all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  setup-oracle:
    image: bash:5.1.16
    container_name: setup-oracle
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1-oracle
    depends_on:
      metabase-oracle:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    ports:
      - 1521:1521
    hostname: oracle
    environment:
      - ORACLE_PASSWORD=Metasample123
    networks: 
      - metanet1-oracle
    volumes:
      - $PWD/oracle-init-script/sample_data.sql:/container-entrypoint-initdb.d/sample_data.sql
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
networks: 
  metanet1-oracle:
    driver: bridge
