version: '3.9'
services:
  metabase:
    image: metabase/metabase:v0.43.0
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3031:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-app-db"
    networks: 
      - metanet1
    depends_on: 
      - postgres-app-db
  postgres-app-db:
    image: postgres:14.2-alpine
    container_name: postgres-app-db
    hostname: postgres-app-db
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1
  setup:
    image: bash:5.1.16
    container_name: setup
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      - metabase
    command: sh /tmp/metabase-setup.sh metabase:3000
  postgres-data1:
    image: metabase/qa-databases:postgres-sample-12
    container_name: postgres-data1
    ports:
      - 5433:5432
    hostname: postgres-data1
    networks: 
      - metanet1
networks: 
  metanet1:
    driver: bridge
