version: '3.7'
services:
  haproxy:
    image: haproxy:lts-alpine
    hostname: haproxy
    container_name: haproxy
    volumes: 
      - $PWD/config/:/usr/local/etc/haproxy/:ro
    networks:
      - metanet-private
      - metanet-public
    ports:
      - 8080:80
  metabase_ha1:
    image: metabase/metabase:v0.42.3
    hostname: metabase_ha1
    container_name: metabase_ha1
    environment:
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_PORT=5432"
      - "MB_DB_HOST=postgres_shared"
      - "MB_DB_TYPE=postgres"
    networks:
      - metanet-private
      - metanet-db
    depends_on:
      - postgres_shared
  metabase_ha2:
    image: metabase/metabase:v0.42.3
    hostname: metabase_ha2
    container_name: metabase_ha2
    environment:
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_PORT=5432"
      - "MB_DB_HOST=postgres_shared"
      - "MB_DB_TYPE=postgres"
    networks:
      - metanet-private
      - metanet-db
    depends_on:
      - postgres_shared
  setup:
    image: bash:5.1.16
    container_name: setup
    networks:
      - metanet-private
    depends_on:
      - metabase_ha1
    command: > 
      sh -c "apk add curl jq && \
        curl -L 'https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until' -o /usr/local/bin/wait-until && \
        chmod +x /usr/local/bin/wait-until && \
        wait-until \"echo 'Checking if Metabase is ready' && curl -s 'http://metabase_ha1:3000/api/health' | grep -ioE \"ok\"\" 60 && \
        if curl -s 'http://metabase_ha1:3000/api/session/properties' | jq -r '.\"setup-token\"' | grep -ioE \"null\"; then echo 'Instance already configured, exiting'; else \
        echo 'Setting up the instance' && \
        token=$$(curl -s http://metabase_ha1:3000/api/session/properties | jq -r '.\"setup-token\"') && \
        echo 'Setup token fetched, now configuring with:' && \
        echo \"{'token':'$$token','user':{'first_name':'a','last_name':'b','email':'a@b.com','site_name':'metabot1','password':'metabot1','password_confirm':'metabot1'},'database':null,'invite':null,'prefs':{'site_name':'metabot1','site_locale':'en','allow_tracking':'false'}}\" > file.json && \
        sed 's/'\''/\"/g' file.json > file2.json && \
        cat file2.json && \
        curl -s http://metabase_ha1:3000/api/setup -H 'Content-Type: application/json' --data-binary @file2.json && echo ' < Admin session token, exiting'; fi"
  postgres_shared:
    image: postgres:14.2-alpine
    container_name: postgres_shared
    hostname: postgres_shared
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - $PWD/postgres_shared:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - metanet-db
networks: 
  metanet-private:
    driver: bridge
  metanet-public:
    driver: bridge
  metanet-db:
    driver: bridge