version: '2'

services:
  postgres:
    container_name: postgres
    ports:
      - "5433:5432"
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    volumes:
      - '$PWD/server.crt:/var/lib/postgresql/server.crt:ro'
      - '$PWD/server.key:/var/lib/postgresql/server.key:ro'
      - '$PWD/pg_hba.conf:/var/lib/postgresql/pg_hba.conf'
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
